// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-OWdR3m4r7CQjrwzHezRXT6NbZ80eVOs',
    appId: '1:947646392748:web:4ea0efba5a60d240cdb209',
    messagingSenderId: '947646392748',
    projectId: 'wandering-2b097',
    authDomain: 'wandering-2b097.firebaseapp.com',
    storageBucket: 'wandering-2b097.firebasestorage.app',
    measurementId: 'G-46BPG60EPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAkL3QQLHpU1oTsRZ2rnVLseG8UYtnhf0',
    appId: '1:947646392748:android:0cc4109cda940f22cdb209',
    messagingSenderId: '947646392748',
    projectId: 'wandering-2b097',
    storageBucket: 'wandering-2b097.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWm_63KmmX9cdwAud0AZJFGjMlslXNtDQ',
    appId: '1:947646392748:ios:004028cbecd264fccdb209',
    messagingSenderId: '947646392748',
    projectId: 'wandering-2b097',
    storageBucket: 'wandering-2b097.firebasestorage.app',
    iosBundleId: 'tw.cycugdgoc.wandering.ios',
  );
}